name: Build and Deploy

on:
  push:
    branches:
      - main  # Set a branch to trigger deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install and Build 
      run: |
        npm install
        npm run build  # Replace this with actual build command

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Adjust this to directory where resume.pdf is located
        publish_branch: gh-pages  # GitHub Pages branch
        user_name: 'github-actions[bot]'  # GitHub Actions bot
        user_email: 'github-actions[bot]@users.noreply.github.com'  # GitHub Actions bot email
        commit_message: 'Automated deployment to GitHub Pages on ${GITHUB_REF} @ ${GITHUB_SHA} by GitHub Actions'
